name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: BitDEVil2K16/VuePagesAction@1.0.0
      with:
        username: 'clementRTB2'
        reponame: 'reaction-timer'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
